### ISSUE TITLE
neo4j?

### ISSUE THREAD

**Issue by santiagogg** [emiliorizzo/vue-d3-network#1]
Hello Emilio! , I found this repo and it was really useful to see what you did. I'm trying to do an UI for Neo4j Database. I do not know if you're familiarised with this but I wanted to know if you'd be interested to support it in the future?

gracias genio :D

**Comment by emiliorizzo** [comment]
Hi Santiago!, Thanks for your comments. 
I don't understand what exactly you need.
If you need help, feel free to contact me at twitter. (@emiliorizzo)
Thank You!
