### ISSUE TITLE
Link color

### ISSUE THREAD

**Issue by gerwinov** [emiliorizzo/vue-d3-network#10]
Hi Emilio,

This component is highly appreciated! 
One question; is it possible to set the color of each link separately (similar to how we can color the nodes)?

Best regards,
Gerwin

**Comment by emiliorizzo** [comment]
thanks for suggestion!
https://jsfiddle.net/emii/ru24unsz/

**Comment by gerwinov** [comment]
Hi Emilio,

Thanks for the quick implementation of this feature!

Regards,
Gerwin

**Comment by emiliorizzo** [comment]
:+1:
