### ISSUE TITLE
Performance in Safari/Firefox

### ISSUE THREAD

**Issue by gerwinov** [emiliorizzo/vue-d3-network#11]
Hi Emilio,

I am currently using this component and try to render a graph with ~450 nodes and ~1600 links. This renders just fine in Chrome, but in Safari and Firefox there seems to be a lag in the animation when loading the graph (the framerate seems to drop). This also happens to your example when creating a lot of nodes with a lot of links (https://emiliorizzo.github.io/vue-d3-network/). Do you recognize this issue and maybe know a solution for this?

Thanks in advance!

Best regards,
Gerwin

**Comment by emiliorizzo** [comment]
I have no problems with 500 nodes / 10 links per node in firefox quantum / linux, but it is possible.
Are you using canvas or svg?
If you can, provide a link to the code.

**Comment by gerwinov** [comment]
Hi Emilio,

I am using SVG. I created a JSFiddle to show the relevant parts of my code. If I run this Fiddle in Chrome it works just fine, if I run it in Firefox it lags. I am on a Macbook Pro btw.

JSFiddle can be found here: https://jsfiddle.net/gerwinov/58k7ujo0/3/

Do you have any recommendations regarding the code?

Thanks in advance!

Best regards,
Gerwin

**Comment by emiliorizzo** [comment]
Sorry @gerwinov, at this time I dont known how improve the svg performance on Safari/Firefox.
I will to continue investigate.
