### ISSUE TITLE
Is it possible to stop the flying nodes when new data is coming?

### ISSUE THREAD

**Issue by bluegray1015** [emiliorizzo/vue-d3-network#13]
Firstly, this project is really useful and helpful, thanks for your contribution.
I encounter a problem. I need to pull the new data back every 5 seconds, and when the data is changed, the nodes are flying into the center. Can I add any argument in the `options` to stop the flying nodes when we do refresh the data?

**Comment by emiliorizzo** [comment]
Hi @bluegray1015 , thanks for your comments!
I do not understand the problem completely. Maybe if you provide a link to the code, I can understand well.
In the main example you can add nodes (linked to anothers) without flying.....
