### ISSUE TITLE
Auto update on links change

### ISSUE THREAD

**Issue by shaunelliot** [emiliorizzo/vue-d3-network#14]
Hi Emilio,

Thanks for this component, it's awesome!

Issue was coding...

Thanks!

**Comment by emiliorizzo** [comment]
Hi! thanks for your comment, I do not understand the issue , please explain.

**Comment by shaunelliot** [comment]
My bad. I originally explained the issue but later realized that it was a coding problem on my end.

Thanks

**Comment by emiliorizzo** [comment]
:+1:
