### ISSUE TITLE
Thank you so much! but need some help request

### ISSUE THREAD

**Issue by lim-enhui** [emiliorizzo/vue-d3-network#18]
is it possible to add the circle and link visible property?  like isVisibleSetFalse: true 
basically i wish to toggle the root and tid linked to the node aka children can be toggled. Hope you would give me an idea. :)

**Comment by emiliorizzo** [comment]
Do you want draw hidden nodes and links?

**Comment by lim-enhui** [comment]
Yes. The idea would be like to recursive set the property to set whether to display the node of the parent node were to be clicked. It will be much easier for me to define svgattribute. As I may use svg attributes for other purposes.

**Comment by emiliorizzo** [comment]
If you need add svg attributes per node, you can:

**_svgAttrs**: Object, svg node attributes
