### ISSUE TITLE
Event not $on does not catch "node-click" event

### ISSUE THREAD

**Issue by jobnomade** [emiliorizzo/vue-d3-network#19]
Hi,

I would like to listen to the click event on the nodes $on('node-click').
I have added a method
```	
displayIcoDetails(){
	this.$on('node-click', function (node) {
	console.log(node);
	});
}
```

the method is called in the `mounted` section. I expect as soon a node is clicked, the console logs the data from the clicked node to the console.
However, I don't receive any information.  No exception or error occurs.
Would be great if you can point me in the right direction.

Thanks!

**Comment by lim-enhui** [comment]
:node-click='' I don't know other way of using it. But basically it is a props to receive methods.

**Comment by jobnomade** [comment]
@lim-enhui thanks for your comment. However that is not the smooth solution I am looing for. As the nodes are build by the library and the attribute which you provide requires to manipulate the DOM elements attributes which would be a way too complicated.

When you look at the vue.js documentation you see https://vuejs.org/v2/api/#vm-on that there is an emitter for the event. The vue-d3-network library emits the event as followed:

```
// -- Render helpers
    nodeClick (event, node) {
      this.$emit('node-click', event, node)
    },
    linkClick (event, link) {
      this.$emit('link-click', event, link)
    },
```
Source: https://github.com/emiliorizzo/vue-d3-network/blob/9c2e7af29a230d6d37470f833e9a67c5fff15d25/src/vue-d3-network.vue#L366

The documentation says

> node-click: fired when click on node, emits (event,node-object)

So I tried to catch the event to trigger my logic. Basically, I want to call additional information from an API to be displayed in a DOM element. But I don't see the event is being fired. That's my problem.

**Comment by emiliorizzo** [comment]
Hi @jobnomade I don't understand what do you need.
@node-click="nodeClick"
nodeClick(event,node){
  console.log(event,node)
// event is mouse click event, or touchEvent
// node is node object 
}

see this fiddle: https://jsfiddle.net/adbbdngx/1/
Do you need a ref to access to node dom element?

**Comment by jobnomade** [comment]
@emiliorizzo I see! I assumed that I can listen to the "node-click" event without adding the attribute. My bad, I am re-learning vue 2.x, had my first steps in 0.12v. Thanks!

**Comment by emiliorizzo** [comment]
👍
