### ISSUE TITLE
Custom Force example needed

### ISSUE THREAD

**Issue by lim-enhui** [emiliorizzo/vue-d3-network#25]
Hi, how do you define custom force... I dont see any examples. Would appreciate any help given.
        this.force = d3.layout.force()
            .linkDistance(60)
            .charge(-50)
            .gravity(0.05)

**Comment by emiliorizzo** [comment]
Maybe this?
https://jsfiddle.net/emii/4odfweq9/

**Comment by lim-enhui** [comment]
Thank you so much!

**Comment by dcorn068** [comment]
Hi, thanks for the library!
Is there a way to implement a custom clustering force? like in https://bl.ocks.org/mbostock/7882658
Or any examples on using the "customForces: Object: { [d3Function]:args }"?

**Comment by emiliorizzo** [comment]
Hi @dcorn068,
https://bl.ocks.org/mbostock/7882658, uses d3.layout (d3-hierachy library) my module support d3-force only.

**Custom Forces**
Available forces: https://github.com/d3/d3-force#forces
example: https://jsfiddle.net/emii/xyc0ztma/
