### ISSUE TITLE
Link shapes in live example have fill

### ISSUE THREAD

**Issue by mootari** [emiliorizzo/vue-d3-network#26]
I just noticed that in your live example on https://emiliorizzo.github.io/vue-d3-network/ the `.link` paths still have a fill. This leads to artifacts when disabling the "Straight links" option.

<img width="533" src="https://user-images.githubusercontent.com/322014/37805782-9c70c79a-2e3c-11e8-9655-4c7a8f994a0c.png">

**Comment by emiliorizzo** [comment]
Thanks for reporting, but I don't find the issue.

![v3-d3-net](https://user-images.githubusercontent.com/3934196/40629584-925cd9fc-62a2-11e8-9000-549b7f8955bf.png)

**Comment by mootari** [comment]
I checked again: It's marked nodes that are affected. 

<img width="1292" alt="marked-nodes" src="https://user-images.githubusercontent.com/322014/40631069-0325c802-62d9-11e8-8803-fb19b4fb2aac.png">

**Comment by emiliorizzo** [comment]
Oops is a bug in svgRenderer component.
I will fix now.
Thank you very much
:+1:
