### ISSUE TITLE
Node labels inside node shape?

### ISSUE THREAD

**Issue by Sadin** [emiliorizzo/vue-d3-network#29]
Could some one point me in the right direction of modifying this so the labels will show inside the nodes rather than float to the side of them?

**Comment by emiliorizzo** [comment]
You are using svg renderer?
In this case if you really need the label 'in´ the shape, you can use 'node.svgSym' option to pass each node labeled svg as sprite. 
But if you only need the label over node shape, you can render the labels by yourself using the nodes positions.
