### ISSUE TITLE
Error in jsfiddle example

### ISSUE THREAD

**Issue by vdidonato** [emiliorizzo/vue-d3-network#3]
In your jsdiffle (https://jsfiddle.net/emii/ru24unsz/) there is an error in the console: 
    Cannot read property 'w' of undefined
        at VueComponent.onResize (vue-d3-network.js:3080)
        at VueComponent.boundFn [as onResize] (....)

I don't know the reason...but I wanted to let you know

**Comment by emiliorizzo** [comment]
@vdidonato Thanks for report! 
:+1:
