### ISSUE TITLE
Rendering Behavior to toggle a visible state of a node

### ISSUE THREAD

**Issue by lim-enhui** [emiliorizzo/vue-d3-network#30]
![image](https://user-images.githubusercontent.com/13527348/41805506-5c7ae568-76de-11e8-8f75-f4187dc18484.png)

In this image above you can see the node 2 is awkward position...

that is because i have an element that is computed and set visible to false, only to be revealed in later toggle manner

![image](https://user-images.githubusercontent.com/13527348/41805523-962ffe88-76de-11e8-87b2-ee75ddd81c1c.png)

I amended the code in the svg 
in line 16:         path(v-for="link in _links"
in line 28: template(v-for='(node,key) in _nodes')

`    _nodes () {
      return this.nodes.filter((el) => el.visible)
    },
    _links () {
      return this.links.filter((el) => el.visible)
    }`

So maybe you can give me some hindsight of behavior pattern

**Comment by lim-enhui** [comment]
![image](https://user-images.githubusercontent.com/13527348/41805545-21ef6422-76df-11e8-8754-f746de5e8124.png)
This extra pic is to show there is no connected link path to result the node in the state position.

**Comment by lim-enhui** [comment]
Hi emiliorizzo,

https://github.com/lim-enhui/vue-infoland-demo

here is the repo to see the results of rendering..

**Comment by lim-enhui** [comment]
Hi I have encounter more issues with the code that I am trying to fix around...
![capture](https://user-images.githubusercontent.com/13527348/42041133-d20a6080-7b23-11e8-94da-f5e9e09d4d96.PNG)

basically when i try to use touch to drag the nodes, it just stuck some where as above...

![capture2](https://user-images.githubusercontent.com/13527348/42041169-eb53174e-7b23-11e8-9b91-48d88f3de061.PNG)
as you can see the node became fixed position. only for touch..

However, everything seems fine with mouse drag though. hope to hear from you soon.

**Comment by emiliorizzo** [comment]
Hello @lim-enhui 
About the 'visible state':
You suggest to add a 'visible' property to nodes?
Why not add / remove the nodes from data source?

Touch support:
Works fine in my projects and the demo, I dont known why not in your project.
I think it would be faster to evaluate a jsfiddle / codepen  than your entire application

**Comment by lim-enhui** [comment]
Can't do that.. cause it will cause rerendering behavior which makes the toggle behavior that switch visible state to rerender the elements.

**Comment by lim-enhui** [comment]
ok i think i know the cause.. basically when you drag with mouse or touch it emits click event with touchend and @click.. but when you want to drag you dont intend to have click behavior... I am going to work on the behavior somehow...

**Comment by emiliorizzo** [comment]
Feel free to open a new issue for node touch

**Comment by emiliorizzo** [comment]
@lim-enhui See this example: https://codepen.io/emilio/pen/MPpWQy
