### ISSUE TITLE
How can i zoom and pan the network SVG?

### ISSUE THREAD

**Issue by giva9712** [emiliorizzo/vue-d3-network#32]
I try to zoom & pan the network svg. Is there any example code in here? Please help me, Thanks for making useful repository.

**Comment by guibragamonte** [comment]
You tryed use `options.force` prop?

### Little snippet

**Template**

```html
<d3-network :options="options"></d3-network>
```

**State**
```javascript
options: { force: 1000 }
```

**Comment by emiliorizzo** [comment]
@giva9712, @GuiBCa sorry for delayed reply.
Zoom is not implemented yet.
