### ISSUE TITLE
customizing stroke-width of each link

### ISSUE THREAD

**Issue by knackjax** [emiliorizzo/vue-d3-network#38]
A feature request, it would be nice if we could override the default lineWidth like how you did with _color.

I tried to use _svgAttrs: {"stroke-width": 10} but it does not seem to override the default. 

https://jsfiddle.net/aym91pek/

Can you either allow overriding via _svgAttrs or make a linkWidth property settable on a per node basis?

Thanks,

**Comment by dacom-dark-sun** [comment]
Same request!.

**Comment by dacom-dark-sun** [comment]
We use it for build LifeWheel and graph of interest. It would be very applied.

**Comment by emiliorizzo** [comment]
Hi @knackjax , @dacom-dark-sun 
 please check: https://codepen.io/emilio/pen/mwYpbj
