### ISSUE TITLE
width and height of svg symbols

### ISSUE THREAD

**Issue by vdidonato** [emiliorizzo/vue-d3-network#4]
I tried to use svg symbols for nodes. This is my HTML.

        <body>
            <div id="app">
                <svg>
                    <symbol id="sym01" viewBox="0 0 100 100"><circle cx="50" cy="50" r="45" stroke-width="5"stroke="blue" fill="red"/></symbol>
                </svg>
                <d3-network :net-nodes="nodes" :net-links="links" :options="options"></d3-network>
            </div>
        </body>

and then in my nodes list I have:

    { id: 2, name: 'my node 2', svgSym: '<svg class="icon"><use xlink:href="#sym01" /></svg>'}

1. Am I using symbols correctly?
2. In the graph options I have nodeSize: 50 and this makes 'regular' nodes have width and height equal to 50 (radius is 25), but it makes my 'special' node with id:2 have width and height equal to 25 (radius is 12.5). I guess somewhere you have something that defines width and height of the embedded svg as half of the value specified in the nodeSize attribute. Is this discrepancy intentional?

A jsfiddle here: https://jsfiddle.net/valenz/ung6t3w4/

**Comment by emiliorizzo** [comment]
1- No, use an svg doc, not a symbol, maybe the name of the prop is confuse.
2 yes, was intentional, but I don't remember why :smile: , I will fix it now.

Working fiddle: https://jsfiddle.net/ung6t3w4/1/

**Comment by emiliorizzo** [comment]
Updated fiddle: https://jsfiddle.net/ung6t3w4/2/
(the labels positions doesn't work with custom sizes...)
