### ISSUE TITLE
[enhancement]: any tutorial plan

### ISSUE THREAD

**Issue by loveJasmine** [emiliorizzo/vue-d3-network#40]

**Comment by loveJasmine** [comment]
app.ee4eef8e.js
is very hard for learning, looks like it was tranformered by some tools

**Comment by loveJasmine** [comment]
my friend tell me app.ee4eef8e.js was encrypted, why not share the source code, I am just learn how to use it

**Comment by emiliorizzo** [comment]
Please, first read the [README](https://github.com/emiliorizzo/vue-d3-network/blob/master/README.md)
