### ISSUE TITLE
what about share the source code of app.ee4eef8e.js and provide more example?

### ISSUE THREAD

**Issue by loveJasmine** [emiliorizzo/vue-d3-network#41]

**Comment by emiliorizzo** [comment]
@loveJasmine the source code is in / src
Please take the time to learn about javascript, vuejs, webpack, etc. before post an issue

**Comment by loveJasmine** [comment]
yes, i am new to javascript, vuejs, webpack and all web dev technology stack.
But I am sure app.ee4eef8e.js is not open sourced, right?

**Comment by emiliorizzo** [comment]
@loveJasmine  You are wrong app.ee4eef8e.js is a distribution file.
The source code of this file is in /src/example.
To rebuild it you can run:
```
My library is open source, please read the [LICENSE](https://github.com/emiliorizzo/vue-d3-network/blob/master/LICENSE)

**Comment by loveJasmine** [comment]
thanks
