### ISSUE TITLE
how to diaplay text(name) for each node and edge, further, can we modified the text on line?

### ISSUE THREAD

**Issue by loveJasmine** [emiliorizzo/vue-d3-network#43]

**Comment by emiliorizzo** [comment]
@loveJasmine  to name a node use 'name' property, see: [README](https://github.com/emiliorizzo/vue-d3-network/blob/master/README.md) and this [example](https://jsfiddle.net/emii/ru24unsz/)

Based on your other questions, I recommend reading: [this](https://vuejs.org/v2/guide/)

**Comment by loveJasmine** [comment]
sure,  I am new to vue and all other web tech like css,js and html etc
