### ISSUE TITLE
Failed to compile with 1 errors    

### ISSUE THREAD

**Issue by zhenchuan** [emiliorizzo/vue-d3-network#44]
ERROR  Failed to compile with 1 errors                                                                                                                      3:57:14 PM

 error  in ./~/vue-d3-network/src/components/canvasRenderer.vue

Module build failed: Unknown word (447:0)

  445 | 
  446 | 
> 447 | canvas
  448 |   position absolute
  449 |   top 0
  450 |   left 0

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-15adbfe7","scoped":false,"hasInlineConfig":false}!./~/stylus-loader?{"sourceMap":false}!./~/postcss-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./~/vue-d3-network/src/components/canvasRenderer.vue 4:14-393
 @ ./~/vue-d3-network/src/components/canvasRenderer.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-d3-network/src/vue-d3-network.vue
 @ ./~/vue-d3-network/src/vue-d3-network.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/clue/report/list.vue
 @ ./src/views/clue/report/list.vue
 @ ./src/routes.js
 @ ./src/main.js

```
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2"
```

**Comment by emiliorizzo** [comment]
```
