### ISSUE TITLE
CSS height seems to be off by 4px

### ISSUE THREAD

**Issue by lksnmnn** [emiliorizzo/vue-d3-network#45]
Hi there,

I am starting to use this component in my BA thesis project.
Since I need more advanced graph manipulation features (like zoom-to-fit, grouping, filtering, ...), I will probably fork this and send you PRs to merge them back, as soon as the thesis was graded (cant publish this before).

One thing that bothers me right now is that the component seems to add 4px to its height, instead of staying in the parents container. I do not have time to investigate this right now, but you mitigated this by using `height: calc(100%-4px);` in the example.

Cheers,
Lukas

**Comment by emiliorizzo** [comment]
Thanks for your comments.
Please provide more information about the issue, like, browser, OS etc.

**Comment by lksnmnn** [comment]
OS: MacOS: 10.13.6
Browser: Chrome (latest)

Here ist the fix you used in your example: https://github.com/emiliorizzo/vue-d3-network/blob/adc5882687155aa133aeab3b2042c6a88ed5e9ff/src/example/d3-net-example.vue#L340

If you remove this, you will see the problem.

Cheers,
Lukas

**Comment by emiliorizzo** [comment]
@lksnmnn The component fits the container.
In the example, I fix the container size because the 100% height setting does not work. If you have an example in where the component exceeds the size of the container, reopen this issue.
Thank you.

**Comment by lksnmnn** [comment]
This is what I meant. The 100% does not work and is off by 4px.
So I thought this happens since the components adds 4px thus with the fix you get 100%.

I will try to create a minimal example or try to find the root cause.
