### ISSUE TITLE
Multiple Links between Two Nodes

### ISSUE THREAD

**Issue by MG1093** [emiliorizzo/vue-d3-network#47]
Is it possible to create 2 or 3 links between 2 nodes. Seems to be overwriting. Typically in networking you would have a primary and secondary link going from 1 router/node to one or multiple router/nodes.

**Comment by emiliorizzo** [comment]
Hi @MG1093 , you can: https://codepen.io/emilio/pen/xemzRw

**Comment by MG1093** [comment]
@emiliorizzo , thank you so much
