### ISSUE TITLE
Does the order of the nodes matter?

### ISSUE THREAD

**Issue by vdidonato** [emiliorizzo/vue-d3-network#5]
This fiddle: https://jsfiddle.net/valenz/977c9cfg/1/ only works if I move the node with id = 0 in the first position of the nodes array. Is there any particular restriction on the nodes order? Is '0' a special id?

**Comment by emiliorizzo** [comment]
No it does not matter.
https://jsfiddle.net/ung6t3w4/3/
I see your fiddle.
The problem is with links declaration no with nodes.
For any reason when te node.id = 0 is not the first.. fail.
This is not a big deal for me. Maybe you can identify the problem in the code and report it to me. Thanks!
