### ISSUE TITLE
Links with arrows and self linking nodes?

### ISSUE THREAD

**Issue by pkovanen** [emiliorizzo/vue-d3-network#50]
Is it possible to draw links as arrows, and also enable self linking nodes?

https://stackoverflow.com/questions/16358905/d3-force-layout-graph-self-linking-node

**Comment by emiliorizzo** [comment]
@pkovanen, About the arrows: threre are more examples at the end of the README.
https://codepen.io/emilio/pen/QOaQjP
The display of self-linked nodes is not available at the moment.
