### ISSUE TITLE
Can you add a button to the node?

### ISSUE THREAD

**Issue by birdle-joe** [emiliorizzo/vue-d3-network#51]
HI,Your example is great.I hope that your component can achieve the click effect similar to neo4j graph database node, click the node can appear buttons, choose to show or hide the node relationship, want to know if you can add buttons in the outer layer of the node, can you give me some suggestions?   thanks.  @emiliorizzo 

![7Z5KL@$9NPT PP(YKJATA5K](https://user-images.githubusercontent.com/42287792/65441776-9256d600-de5d-11e9-987a-d83be15f404d.png)

**Comment by emiliorizzo** [comment]
HI @birdle-joe, please look at this example: https://codepen.io/emilio/pen/xxKMMpY
I used the 'node-click' event to display the dialog, and node coordinates for the labels.

**Comment by birdle-joe** [comment]
@emiliorizzo Thank you  for your reply,It has achieved the desired results.
