### ISSUE TITLE
Link distance

### ISSUE THREAD

**Issue by ekifox** [emiliorizzo/vue-d3-network#53]
![image](https://user-images.githubusercontent.com/1989823/66232217-06f90280-e6f1-11e9-9255-2fbd8df12c8f.png)
https://bl.ocks.org/mbostock/ad70335eeef6d167bc36fd3c04378048
How can I make a network like this? D3 has a line value option to draw a distance between nodes.

**Comment by chamnanso** [comment]
I haven't tried myself. But you can try setting simCb or customForces prop options to 

someFunc(sim) { 

sim.force('link', d3.forceLink(links).id(function (d) {
          return d.id;
        }).strength(0.5));

return sim
}

**Comment by emiliorizzo** [comment]
@ekifox 
You can fix the position of some nodes, see the 'pin' tool in the example.
