### ISSUE TITLE
vue-d3-network freezes when node 'x' and 'y' co-ordinates are set and 40+ nodes used

### ISSUE THREAD

**Issue by BigThoughts** [emiliorizzo/vue-d3-network#66]
I have set up a node graph with around 50 nodes, setting the 'x' and 'y' co-ordinates, along with forces under 'options'. The nodes position as intended, but none of the forces act.

When I re-render the vue-d3-network the nodes move subject to the forces set, but then freeze in place again. (I've added a refresh button as a workaround for now, but not a long term solution)

If I don't set the 'x' and 'y' co-ordinates, the nodes react under the force correctly (but with significant overlapping in the links, which is not desirable, hence the need to set the positions).

Is there any way to fix this behaviour?

Thanks

**Comment by emiliorizzo** [comment]
Please provide a reproduction and feel free to reopen.
