### ISSUE TITLE
vue-d3-network.js.map 404 issue in Safari

### ISSUE THREAD

**Issue by Beraliv** [emiliorizzo/vue-d3-network#7]
The error is this:
`
failed to load resource with 404 error (HTTP/2.0) vue-d3-network.js.map
`

It concerns [my project](https://github.com/Beraliv/vue-vk-friend-graph)

It only occurs in Safari. You can test it in my [demo](https://beraliv.github.io/vue-vk-friend-graph/)

**Comment by emiliorizzo** [comment]
I can't test your project because requires authentication
