### ISSUE TITLE
Hover and Tooltip

### ISSUE THREAD

**Issue by acarmurat** [emiliorizzo/vue-d3-network#75]
Is there any possibility to show a `tooltip` when `hover`  like 
![image](https://user-images.githubusercontent.com/24543800/89273766-aa37e280-d648-11ea-9bbd-0a3645435cf7.png)

**Comment by emiliorizzo** [comment]
@acarmurat , sorry for the late answer, but the tooltip can be implemented without updating this library. Thanks
