### ISSUE TITLE
Q: Is SVG render template necessary?

### ISSUE THREAD

**Issue by junjizhi** [emiliorizzo/vue-d3-network#78]
https://github.com/emiliorizzo/vue-d3-network/blob/a2d4c55eed699d7f769fedc56de95e9fba8f93cd/src/components/svgRenderer.vue#L1-L76

There is a long hand-coded template with svg code. Can it be replaced with simpler `d3.select()` calls to render the element?

**Comment by emiliorizzo** [comment]
@junjizhi  Thanks for the suggestion, but I prefer the current design.
